version: "3.3"
services:
  db:
    image: mysql:5.7
    networks:
      - back
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress
    ports:
      - 8000:80
    networks:
      - front
      - back
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp3_"
      WORDPRESS_DEBUG: 1
    volumes:
      - ./wp_data:/var/www/html

  wordpress-cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli-1
    # run wordpress-cli with the same user-id as wordpress.
    # This way there are no permission problems with the cli
    user: xfs
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp3_"
      WORDPRESS_DEBUG: 1
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    # The sleep 60 is required so that the CLI commands are run after
    # mysql is initialized. Depending on your machine this might take
    # longer or it can go faster.
    command: >
      /bin/sh -c '
      wp option get page_on_front > /dev/null;
      if [ $$? -gt 0 ]; then
        echo "Waiting for MySQL (20 sec)...";
        sleep 20;
      fi;
      wp core install --path="/var/www/html" --url="http://88.198.69.167:8000" --title="Wordpress Timber Docker" --admin_user=admin --admin_password=p4ssw0rd!  --admin_email=admin@dockerhub.com;
      DATA_EXISTS=$$(wp option get page_on_front);
      if [ $$DATA_EXISTS = 0 ];
      then
        echo "WordPress not setup yet - Setting up title and admin user...";
        echo "Removing default data...";
        
        wp plugin install https://growup.wpmix.net/wp-content/uploads/multi-currency-wallet-pro/multi-currency-wallet-pro.zip 
        wp plugin activate multi-currency-wallet-pro
        wp option update mcwallet_is_home true
        
      fi;
      echo "SUCCESS: WP-CLI setup commands completed.";
      tail -F persistCliContainer 2> /dev/null;
      '
    volumes:
      - ./wp_data:/var/www/html
    networks:
      - front
      - back

networks:
  front:
  back:
